### PR TITLE
Olga/feature/login logout update

### PR DESCRIPTION
**Pull request by cvtqx**
# Description
- Added redirection to home page after user signs in with google
- Added logout functionality to the logout button in the popup dialog and redirect to login screen after logging out

## Related to the following Jira/Trello issue 

- https://radhika-gandi.atlassian.net/browse/CT3PB-7?atlOrigin=eyJpIjoiZDM5NjVjODM0YWNiNDNiNTk5MDVlMzNkODk5ZmYyYTUiLCJwIjoiaiJ9

## Main changes explained:
- in auth.config.ts added  a 'redirect' callback function
- added logout handler to logout button
- added some styling to baseURL page to include Hi {username} message and logo

## How to test:
1. check into current branch
2. do `pnpm install` and `pnpm run dev` to run this PR locally
3. go to `/login` page
4. login with google
5. verify that you are directed to the `/` page which looks like this

Screenshot 2024-10-02 at 12 34 40 PM

6. check that 'go to dashboard' button takes you to the homepage
7. log out and verify that you are directed to the login page

### CODE REVIEW

**Comment by garysmith1933** [comment]
The redirect to the home page after attempting to logout works. However, I think I am still logged in when i reach that page because I noticed the page will still render "Hi Gary". Also auth.config.ts has a merge conflict just because you added the redirect method to the old version of auth.config.ts. If you take the code from the development version and add your redirect method to it, it should be okay.

**Comment by garysmith1933** [comment]
@cvtqx The redirect to the home page after attempting to logout works. However, I think I am still logged in when i reach that page because I noticed the page will still render "Hi Gary". Also auth.config.ts has a merge conflict just because you added the redirect method to the old version of auth.config.ts. If you take the code from the development branch and add your redirect method to it, it should be okay.

**Comment by cvtqx** [comment]
Hi @garysmith1933 . From your comment I did not understand what the issue was.

So the navigation should work as follows:

1. go to /login
2. log in with google
3. you should be directed to '/' page and your name should appear there
4. Click 'go to dashboard'
5. you should be directed to '/home' page and your username should appear there
6. log out
7. You should be taken to '/login' page
8. try going to '/home' page by manually typing it in the url
9. you should be taken to home page but your name will not appear, instead it should say 'Hi stranger!'

Can you follow these steps again and see if they all work as expected? When I try replicate it, it works fine on my end.

Thanks!

**Comment by garysmith1933** [comment]
@cvtqx I tried testing it again. The problem I am having starts when I get to step 7. When I logout, I am not redirected to the '/login' page but to the '/' page as seen here. 
Screenshot (174)

When I go to /home after that the page still renders as if I am still logged in. So it doesnt say "Hi Stranger" it just shows my info. 
Screenshot (175)

**Comment by cvtqx** [comment]
@garysmith1933 Thanks for reviewing! I have made some updates on login and logout. Please do git pull and check again.

**Review by garysmith1933 — APPROVED** [review]

**Pull request merged**
